// default package
// Generated Dec 3, 2013 5:07:03 PM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.springframework.transaction.annotation.Transactional;

/**
 * Deployjob generated by hbm2java
 */
@Entity
@Table(name = "deployjob", catalog = "docs")
public class Deployjob implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5531572045860750808L;
	private Long id;
	private String ldapname;
	private String groupid;
	private String artifactid;
	private String warname;
	private String pomname;
	private String type;
	private Long starttime;
	private Long endtime;
	private Status status;
	private String failreason;

	public Deployjob() {
	}

	public Deployjob(String ldapname, String groupid, String artifactid,
			String warname, long starttime) {
		this.ldapname = ldapname;
		this.groupid = groupid;
		this.artifactid = artifactid;
		this.warname = warname;
		this.starttime = starttime;
	}

	public Deployjob(String ldapname, String groupid, String artifactid,
			String warname, String pomname, String type, long starttime,
			Long endtime, Status status, String failreason) {
		this.ldapname = ldapname;
		this.groupid = groupid;
		this.artifactid = artifactid;
		this.warname = warname;
		this.pomname = pomname;
		this.type = type;
		this.starttime = starttime;
		this.endtime = endtime;
		this.status = status;
		this.failreason = failreason;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ldapname", nullable = false, length = 70)
	public String getLdapname() {
		return this.ldapname;
	}

	public void setLdapname(String ldapname) {
		this.ldapname = ldapname;
	}

	@Column(name = "groupid", nullable = false, length = 100)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "artifactid", nullable = false, length = 100)
	public String getArtifactid() {
		return this.artifactid;
	}

	public void setArtifactid(String artifactid) {
		this.artifactid = artifactid;
	}

	@Column(name = "warname", nullable = false, length = 100)
	public String getWarname() {
		return this.warname;
	}

	public void setWarname(String warname) {
		this.warname = warname;
	}

	@Column(name = "pomname", length = 100)
	public String getPomname() {
		return this.pomname;
	}

	public void setPomname(String pomname) {
		this.pomname = pomname;
	}

	@Column(name = "type", length = 7)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "starttime", nullable = false)
	public long getStarttime() {
		return this.starttime;
	}

	public void setStarttime(long starttime) {
		this.starttime = starttime;
	}

	@Column(name = "endtime")
	public Long getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Long endtime) {
		this.endtime = endtime;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status")
	@Transactional
	@JsonIgnore
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "failreason", length = 100)
	public String getFailreason() {
		return this.failreason;
	}

	public void setFailreason(String failreason) {
		this.failreason = failreason;
	}
	
	public String toString(){
		StringBuffer retVal=new StringBuffer("");
		retVal.append("{");
		retVal.append("id:"+this.id);
		retVal.append(",artifactid:"+this.artifactid);
		retVal.append(",groupid"+this.groupid);
		retVal.append(",ldapname"+this.ldapname);
		retVal.append(",pomname:"+this.pomname);
		retVal.append(",type:"+this.type);
		retVal.append(",warname:"+this.warname);
		retVal.append("}");
		return retVal.toString();
	}

}
