// default package
// Generated Nov 5, 2013 4:33:57 PM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeployjobsId generated by hbm2java
 */
@Embeddable
public class DeployjobsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7931266457643649291L;
	
	private String ldapname;
	private String groupid;
	private String artifactid;
	private String warname;
	private String pomname;
	private Long starttime;

	public DeployjobsId() {
	}

	public DeployjobsId(String ldapname, String groupid, String artifactid,
			String warname, String pomname, Long starttime) {
		this.ldapname = ldapname;
		this.groupid = groupid;
		this.artifactid = artifactid;
		this.warname = warname;
		this.pomname = pomname;
		this.starttime = starttime;
	}

	@Column(name = "ldapname", nullable = false, length = 70)
	public String getLdapname() {
		return this.ldapname;
	}

	public void setLdapname(String ldapname) {
		this.ldapname = ldapname;
	}

	@Column(name = "groupid", nullable = false, length = 100)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "artifactid", nullable = false, length = 100)
	public String getArtifactid() {
		return this.artifactid;
	}

	public void setArtifactid(String artifactid) {
		this.artifactid = artifactid;
	}

	@Column(name = "warname", nullable = false, length = 100)
	public String getWarname() {
		return this.warname;
	}

	public void setWarname(String warname) {
		this.warname = warname;
	}

	@Column(name = "pomname", nullable = false, length = 100)
	public String getPomname() {
		return this.pomname;
	}

	public void setPomname(String pomname) {
		this.pomname = pomname;
	}

	@Column(name = "starttime", nullable = false)
	public Long getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Long starttime) {
		this.starttime = starttime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeployjobsId))
			return false;
		DeployjobsId castOther = (DeployjobsId) other;

		return ((this.getLdapname() == castOther.getLdapname()) || (this
				.getLdapname() != null && castOther.getLdapname() != null && this
				.getLdapname().equals(castOther.getLdapname())))
				&& ((this.getGroupid() == castOther.getGroupid()) || (this
						.getGroupid() != null && castOther.getGroupid() != null && this
						.getGroupid().equals(castOther.getGroupid())))
				&& ((this.getArtifactid() == castOther.getArtifactid()) || (this
						.getArtifactid() != null
						&& castOther.getArtifactid() != null && this
						.getArtifactid().equals(castOther.getArtifactid())))
				&& ((this.getWarname() == castOther.getWarname()) || (this
						.getWarname() != null && castOther.getWarname() != null && this
						.getWarname().equals(castOther.getWarname())))
				&& ((this.getPomname() == castOther.getPomname()) || (this
						.getPomname() != null && castOther.getPomname() != null && this
						.getPomname().equals(castOther.getPomname())))
				&& (this.getStarttime() == castOther.getStarttime());
	}

	public int hashCode() {
		int result = 17;
		long starttime=this.getStarttime();
		int starttimeint=(int)starttime;
		result = 37 * result
				+ (getLdapname() == null ? 0 : this.getLdapname().hashCode());
		result = 37 * result
				+ (getGroupid() == null ? 0 : this.getGroupid().hashCode());
		result = 37
				* result
				+ (getArtifactid() == null ? 0 : this.getArtifactid()
						.hashCode());
		result = 37 * result
				+ (getWarname() == null ? 0 : this.getWarname().hashCode());
		result = 37 * result
				+ (getPomname() == null ? 0 : this.getPomname().hashCode());
		result = 37 * result + starttimeint;
		return result;
	}
	
	public String toString(){
		StringBuffer retVal=new StringBuffer("");
		retVal.append("{artifactid:");
		retVal.append(this.artifactid);
		retVal.append(",groupid:");
		retVal.append(this.groupid);
		retVal.append(",ldapname:");
		retVal.append(this.ldapname);
		retVal.append(",pomname:");
		retVal.append(this.pomname);
		retVal.append(",warname:");
		retVal.append(this.warname);
		retVal.append(",starttime:");
		if(null!=starttime){
		    retVal.append(new SimpleDateFormat("M-dd-yyyy HH:mm:ss").format(new Date(this.starttime)));
		}
		else{
			retVal.append("null");
		}
		retVal.append("}");
		return retVal.toString();
	}

}
