// default package
// Generated Nov 5, 2013 4:33:57 PM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Freeze generated by hbm2java
 */
@Entity
@Table(name = "freeze", catalog = "docs")
public class Freeze implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7349744413718863367L;
	
	private short id;
	private Boolean shouldfreeze;

	public Freeze() {
	}

	public Freeze(short id) {
		this.id = id;
	}

	public Freeze(short id, Boolean shouldfreeze) {
		this.id = id;
		this.shouldfreeze = shouldfreeze;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "shouldfreeze")
	public Boolean getShouldfreeze() {
		return this.shouldfreeze;
	}

	public void setShouldfreeze(Boolean shouldfreeze) {
		this.shouldfreeze = shouldfreeze;
	}

}
