// default package
// Generated Nov 6, 2013 8:59:08 AM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MembersId generated by hbm2java
 */
@Embeddable
public class MembersId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7000163254308187363L;
	
	private String ldapname;
	private String groupname;

	public MembersId() {
	}

	public MembersId(String ldapname, String groupname) {
		this.ldapname = ldapname;
		this.groupname = groupname;
	}

	@Column(name = "ldapname", nullable = false, length = 70)
	public String getLdapname() {
		return this.ldapname;
	}

	public void setLdapname(String ldapname) {
		this.ldapname = ldapname;
	}

	@Column(name = "groupname", nullable = false, length = 90)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MembersId))
			return false;
		MembersId castOther = (MembersId) other;

		return ((this.getLdapname() == castOther.getLdapname()) || (this
				.getLdapname() != null && castOther.getLdapname() != null && this
				.getLdapname().equals(castOther.getLdapname())))
				&& ((this.getGroupname() == castOther.getGroupname()) || (this
						.getGroupname() != null
						&& castOther.getGroupname() != null && this
						.getGroupname().equals(castOther.getGroupname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLdapname() == null ? 0 : this.getLdapname().hashCode());
		result = 37 * result
				+ (getGroupname() == null ? 0 : this.getGroupname().hashCode());
		return result;
	}

}
