// default package
// Generated Nov 6, 2013 8:59:08 AM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Members generated by hbm2java
 */
@Entity
@Table(name = "members", catalog = "docs")
public class Members implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8246141032536301126L;
	private MembersId id;

	public Members() {
	}

	public Members(MembersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ldapname", column = @Column(name = "ldapname", nullable = false, length = 70)),
			@AttributeOverride(name = "groupname", column = @Column(name = "groupname", nullable = false, length = 90)) })
	public MembersId getId() {
		return this.id;
	}

	public void setId(MembersId id) {
		this.id = id;
	}

}
