// default package
// Generated Nov 5, 2013 4:33:57 PM by Hibernate Tools 3.4.0.CR1
package com.rackspace.cloud.api.entity;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.springframework.transaction.annotation.Transactional;


/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "docs")
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7599576906645991212L;
	
	private String value;
	private Set<Deployjob> deployjobs = new HashSet<Deployjob>(0);

	public Status() {
	}

	public Status(String value) {
		this.value = value;
	}

	public Status(String value, Set<Deployjob> deployjobs) {
		this.value = value;
		this.deployjobs = deployjobs;
	}

	@Id
	@Column(name = "value", unique = true, nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	@Transactional
	@JsonIgnore
	public Set<Deployjob> getDeployjobs() {
		return this.deployjobs;
	}

	public void setDeployjobs(Set<Deployjob> deployjobs) {
		this.deployjobs = deployjobs;
	}

	public String toString(){
		StringBuffer retVal=new StringBuffer("");
		retVal.append("{");
		retVal.append("value:"+this.value);
		retVal.append(",deployjobes:"+this.deployjobs);
		retVal.append("}");
		return retVal.toString();
	}
}
